import tkinter as tk

window = tk.Tk()
window.title("Tkinter Text Boxes")

# Row 1, Column 0
# label1 = tk.Label(window, text="First Step")
# label1.grid(row=0, column=0, padx=10, pady=5, sticky="e")
# textbox1 = tk.Text(window, wrap=tk.WORD, height=1, width=20)
# textbox1.grid(row=0, column=1, padx=10, pady=5)

# Row 1, Column 1
label2 = tk.Label(window, text="Type the tabname to attack:")
label2.grid(row=1, column=2, padx=10, pady=5, sticky="e")
textbox2 = tk.Text(window, wrap=tk.WORD, height=1, width=20)
textbox2.grid(row=1, column=3, padx=10, pady=5)
tabname = textbox2.get("1.0","end-1c")

# Row 1, Column 2 (First Text Box)
label3 = tk.Label(window, text="Type the name of column containing usernames:")
label3.grid(row=0, column=4, padx=10, pady=5, sticky="e")
textbox3_1 = tk.Text(window, wrap=tk.WORD, height=1, width=20)
textbox3_1.grid(row=0, column=5, padx=10, pady=5)
user_input = textbox3_1.get("1.0","end-1c")

# Row 1, Column 2 (Second Text Box)
label4 = tk.Label(window, text="Type the name of the column containing passwords:")
label4.grid(row=1, column=4, padx=10, pady=5, sticky="e")
textbox3_2 = tk.Text(window, wrap=tk.WORD, height=1, width=20)
textbox3_2.grid(row=1, column=5, padx=10, pady=5)
password_input = textbox3_2.get("1.0","end-1c")


label5 = tk.Label(window, text="Type the name of the column containing passwords:")
label5.grid(row=1, column=7, padx=10, pady=5, sticky="e")
textbox_target_user = tk.Text(window, wrap=tk.WORD, height=1, width=20)
textbox_target_user.grid(row=1, column=8, padx=10, pady=5)
target_user = textbox_target_user.get("1.0","end-1c")

# Row 2, Text Box 4 (Read-Only)
label4 = tk.Label(window, text="Text Box 4")
label4.grid(row=2, column=0, padx=10, pady=5, sticky="e")
frame4 = tk.Frame(window)
frame4.grid(row=2, column=1, padx=10, pady=5)
textbox4 = tk.Text(frame4, wrap=tk.WORD, height=5, width=20)
textbox4.insert(tk.END, "")
#textbox4.config(state=tk.DISABLED)
textbox4.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
scrollbar4 = tk.Scrollbar(frame4, command=textbox4.yview)
scrollbar4.pack(side=tk.RIGHT, fill=tk.Y)
textbox4.config(yscrollcommand=scrollbar4.set)

# Row 2, Text Box 5 (Read-Only)
label5 = tk.Label(window, text="Text Box 5")
label5.grid(row=2, column=2, padx=10, pady=5, sticky="e")
frame5 = tk.Frame(window)
frame5.grid(row=2, column=3, padx=10, pady=5)
textbox5 = tk.Text(frame5, wrap=tk.WORD, height=5, width=20)
textbox5.insert(tk.END, "")
#textbox5.config(state=tk.DISABLED)
textbox5.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
scrollbar5 = tk.Scrollbar(frame5, command=textbox5.yview)
scrollbar5.pack(side=tk.RIGHT, fill=tk.Y)
textbox5.config(yscrollcommand=scrollbar5.set)

# Row 2, Text Box 6 (Read-Only)
label6 = tk.Label(window, text="Text Box 6")
label6.grid(row=2, column=4, padx=10, pady=5, sticky="e")
frame6 = tk.Frame(window)
frame6.grid(row=2, column=5, padx=10, pady=5)
textbox6 = tk.Text(frame6, wrap=tk.WORD, height=5, width=20)
textbox6.insert(tk.END, "")
#textbox6.config(state=tk.DISABLED)
textbox6.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
scrollbar6 = tk.Scrollbar(frame6, command=textbox6.yview)
scrollbar6.pack(side=tk.RIGHT, fill=tk.Y)
textbox6.config(yscrollcommand=scrollbar6.set)

label7 = tk.Label(window, text="Text Box 7")
label7.grid(row=2, column=7, padx=10, pady=5, sticky="e")
frame7 = tk.Frame(window)
frame7.grid(row=2, column=8, padx=10, pady=5)
textbox7 = tk.Text(frame7, wrap=tk.WORD, height=5, width=20)
textbox7.insert(tk.END, "")
#textbox7.config(state=tk.DISABLED)
textbox7.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
scrollbar7 = tk.Scrollbar(frame7, command=textbox7.yview)
scrollbar7.pack(side=tk.RIGHT, fill=tk.Y)
textbox7.config(yscrollcommand=scrollbar7.set)

# Run the application
window.mainloop()